name: Build ESP32 Firmware

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install required libraries
        run: |
          arduino-cli lib install "DHT sensor library"
          arduino-cli lib install "ArduinoJson"

      - name: Debug file structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "esp32_dht22_prometheus directory contents:"
          ls -la esp32_dht22_prometheus/

      - name: Create build directory
        run: mkdir -p build

      - name: Build firmware
        run: |
          cd esp32_dht22_prometheus
          arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --output-dir ../build \
            --export-binaries \
            esp32_dht22_prometheus.ino

      - name: Rename binary with version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.version }}
          fi
          cp build/esp32_dht22_prometheus.ino.bin build/esp32_dht22_prometheus_${VERSION}.bin

      - name: Generate checksums
        run: |
          cd build
          sha256sum *.bin > checksums.txt

      - name: Debug build output
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Looking for binary files:"
          find build/ -name "*.bin" -type f

      - name: Upload firmware to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/esp32_dht22_prometheus_${{ github.ref_name }}.bin
          asset_name: esp32_dht22_prometheus_${{ github.ref_name }}.bin
          asset_content_type: application/octet-stream

      - name: Upload checksums to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain

      - name: Upload build artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: |
            build/esp32_dht22_prometheus_*.bin
            build/checksums.txt
